import React, { useState, useEffect, useCallback } from "react";
import { Course, Teacher, StudentGroup } from "../../types";
import { BookOpen, X, Loader2, FlaskConical, AlertCircle, Wand2, Copy } from "lucide-react";

interface CourseModalProps {
  isOpen: boolean;
  course?: Course | null;
  teachers: Teacher[];
  groups: StudentGroup[];
  existingCourses: Course[];
  existingCourseIds: string[];
  onSave: (data: {
    course_id: string;
    course_name: string;
    weekly_periods: number;
    teacher_id: string;
    lab_required: boolean;
    department?: string;
    color_code?: string;
  }) => Promise<void>;
  onClose: () => void;
}

const DEPARTMENTS = [
  "Mathematics",
  "Science",
  "English",
  "Social Science",
  "Hindi",
  "Technology",
  "Physical Education",
  "Fine Arts",
  "Resource",
  "General",
];

// Generate a course ID from name + optional grade + section
// "Mathematics", grade=9, section="C" → "MATH09_C"
function generateCourseId(
  name: string,
  grade: string,
  section: string,
  existingIds: string[]
): string {
  if (!name.trim()) return "";

  // Build abbreviation: take first 4 uppercase letters of the subject name
  const abbrev = name
    .trim()
    .replace(/[^a-zA-Z\s]/g, "")
    .split(/\s+/)
    .map((w) => w.toUpperCase().charAt(0))
    .join("") || name.trim().replace(/[^a-zA-Z]/g, "").slice(0, 4).toUpperCase();

  // Use first 4 letters of first word if single word
  const firstWord = name.trim().split(/\s+/)[0].replace(/[^a-zA-Z]/g, "").toUpperCase();
  const prefix = firstWord.length >= 4 ? firstWord.slice(0, 4) : abbrev.slice(0, 4);

  const gradeStr = grade ? String(grade).padStart(2, "0") : "";
  const sectionStr = section ? `_${section.toUpperCase()}` : "";

  let base = prefix + gradeStr + sectionStr;

  // Ensure uniqueness
  const upperExisting = existingIds.map((id) => id.toUpperCase());
  if (!upperExisting.includes(base)) return base;

  let counter = 2;
  while (upperExisting.includes(`${base}_${counter}`)) counter++;
  return `${base}_${counter}`;
}

export const CourseModal: React.FC<CourseModalProps> = ({
  isOpen,
  course,
  teachers,
  groups,
  existingCourses,
  existingCourseIds,
  onSave,
  onClose,
}) => {
  const isEdit = !!course;

  const [courseId, setCourseId] = useState("");
  const [idAutoGenerated, setIdAutoGenerated] = useState(true);
  const [courseName, setCourseName] = useState("");
  const [department, setDepartment] = useState("General");
  const [weeklyPeriods, setWeeklyPeriods] = useState(5);
  const [teacherId, setTeacherId] = useState("");
  const [labRequired, setLabRequired] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Smart ID generation helpers
  const [targetGrade, setTargetGrade] = useState("");
  const [targetSection, setTargetSection] = useState("");
  const [copyFromCourseId, setCopyFromCourseId] = useState("");

  useEffect(() => {
    if (course) {
      setCourseId(course.course_id);
      setIdAutoGenerated(false);
      setCourseName(course.course_name);
      setDepartment(course.department || "General");
      setWeeklyPeriods(course.weekly_periods);
      setTeacherId(course.teacher_id);
      setLabRequired(course.lab_required);
      setTargetGrade("");
      setTargetSection("");
      setCopyFromCourseId("");
    } else {
      setCourseId("");
      setIdAutoGenerated(true);
      setCourseName("");
      setDepartment("General");
      setWeeklyPeriods(5);
      setTeacherId(teachers[0]?.teacher_id || "");
      setLabRequired(false);
      setTargetGrade("");
      setTargetSection("");
      setCopyFromCourseId("");
    }
    setError(null);
  }, [course, teachers, isOpen]);

  // Re-generate ID whenever name / grade / section changes in auto mode
  const regenerateId = useCallback(
    (name: string, grade: string, section: string) => {
      if (idAutoGenerated && !isEdit) {
        const newId = generateCourseId(name, grade, section, existingCourseIds);
        setCourseId(newId);
      }
    },
    [idAutoGenerated, isEdit, existingCourseIds]
  );

  const handleNameChange = (name: string) => {
    setCourseName(name);
    regenerateId(name, targetGrade, targetSection);
  };

  const handleGradeChange = (grade: string) => {
    setTargetGrade(grade);
    regenerateId(courseName, grade, targetSection);
  };

  const handleSectionChange = (section: string) => {
    setTargetSection(section);
    regenerateId(courseName, targetGrade, section);
  };

  const handleIdChange = (val: string) => {
    setCourseId(val);
    setIdAutoGenerated(false);
  };

  const resetAutoId = () => {
    setIdAutoGenerated(true);
    setCourseId(generateCourseId(courseName, targetGrade, targetSection, existingCourseIds));
  };

  // Copy from existing course
  const handleCopyFromCourse = (selectedId: string) => {
    setCopyFromCourseId(selectedId);
    const src = existingCourses.find((c) => c.course_id === selectedId);
    if (!src) return;
    setCourseName(src.course_name);
    setDepartment(src.department || "General");
    setWeeklyPeriods(src.weekly_periods);
    setTeacherId(src.teacher_id);
    setLabRequired(src.lab_required);
    // Re-generate new ID based on same name but different section
    if (idAutoGenerated) {
      const newId = generateCourseId(src.course_name, targetGrade, targetSection, existingCourseIds);
      setCourseId(newId);
    }
  };

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    const cleanId = courseId.trim().toUpperCase();
    const cleanName = courseName.trim();

    if (!cleanId) {
      setError("Subject Code (Course ID) is required.");
      return;
    }
    if (!cleanName) {
      setError("Course Name is required.");
      return;
    }
    if (!isEdit && existingCourseIds.map((id) => id.toUpperCase()).includes(cleanId)) {
      setError(`Course ID '${cleanId}' is already in use. Please change the Section or override the ID.`);
      return;
    }
    if (!teacherId) {
      setError("Please select an assigned faculty member.");
      return;
    }
    if (weeklyPeriods < 1 || weeklyPeriods > 20) {
      setError("Weekly periods must be between 1 and 20.");
      return;
    }

    setIsSubmitting(true);
    try {
      await onSave({
        course_id: cleanId,
        course_name: cleanName,
        weekly_periods: Number(weeklyPeriods),
        teacher_id: teacherId,
        lab_required: labRequired,
        department: department.trim() || "General",
      });
      onClose();
    } catch (err: any) {
      setError(err.message || "Failed to save course.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-xs p-4 animate-in fade-in duration-150">
      <div className="bg-white rounded-2xl border border-slate-200 max-w-lg w-full p-6 text-slate-900 shadow-2xl flex flex-col max-h-[95vh]">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-100 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-50 border border-indigo-100 text-indigo-600 flex items-center justify-center shrink-0">
              <BookOpen className="w-5 h-5 stroke-[2.2]" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">
                {isEdit ? "Edit Subject / Course" : "Add New Subject"}
              </h3>
              <p className="text-xs text-slate-500">
                {isEdit ? "Update curriculum details" : "Subject ID is auto-generated from name + grade + section"}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors disabled:opacity-40 cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="py-4 space-y-4 overflow-y-auto flex-1 pr-1">
          {error && (
            <div className="p-3 rounded-xl bg-rose-50 border border-rose-200 flex items-start gap-2.5 text-xs text-rose-800">
              <AlertCircle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          {/* Copy from existing course (Add mode only) */}
          {!isEdit && existingCourses.length > 0 && (
            <div className="p-3 rounded-xl bg-indigo-50 border border-indigo-200">
              <label className="flex items-center gap-1.5 text-xs font-semibold text-indigo-800 mb-2">
                <Copy className="w-3.5 h-3.5" />
                Copy settings from an existing subject
              </label>
              <select
                value={copyFromCourseId}
                onChange={(e) => handleCopyFromCourse(e.target.value)}
                className="w-full bg-white border border-indigo-200 rounded-lg px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              >
                <option value="">(Select a subject to copy its settings)</option>
                {existingCourses.map((c) => (
                  <option key={c.course_id} value={c.course_id}>
                    {c.course_name} — {c.weekly_periods}p/wk ({c.course_id})
                  </option>
                ))}
              </select>
              <p className="text-[10px] text-indigo-600 mt-1">
                This copies name, periods, teacher, and lab settings — but generates a new unique ID.
              </p>
            </div>
          )}

          {/* Grade & Section for ID auto-generation */}
          {!isEdit && (
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Grade Level <span className="text-slate-400 font-normal">(for ID)</span>
                </label>
                <input
                  type="text"
                  value={targetGrade}
                  onChange={(e) => handleGradeChange(e.target.value)}
                  placeholder="e.g. 9 or 10"
                  className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                />
              </div>
              <div>
                <label className="block text-xs font-semibold text-slate-700 mb-1">
                  Section <span className="text-slate-400 font-normal">(for ID)</span>
                </label>
                <input
                  type="text"
                  value={targetSection}
                  onChange={(e) => handleSectionChange(e.target.value)}
                  placeholder="e.g. A or B or C"
                  className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                />
              </div>
            </div>
          )}

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
            {/* Course Name — drives auto-ID */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Course Name <span className="text-rose-500">*</span>
              </label>
              <input
                type="text"
                value={courseName}
                onChange={(e) => handleNameChange(e.target.value)}
                placeholder="e.g. Mathematics"
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                required
                autoFocus={!isEdit && !existingCourses.length}
              />
            </div>

            {/* Department */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Department
              </label>
              <select
                value={department}
                onChange={(e) => setDepartment(e.target.value)}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              >
                {DEPARTMENTS.map((dept) => (
                  <option key={dept} value={dept}>{dept}</option>
                ))}
              </select>
            </div>
          </div>

          {/* Subject Code (auto-generated, editable) */}
          <div>
            <label className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 mb-1">
              Subject Code (ID) <span className="text-rose-500">*</span>
              {!isEdit && idAutoGenerated && (
                <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full bg-indigo-50 border border-indigo-200 text-indigo-700 text-[9px] font-bold">
                  <Wand2 className="w-2.5 h-2.5" /> Auto
                </span>
              )}
            </label>
            <div className="flex gap-1.5">
              <input
                type="text"
                value={courseId}
                onChange={(e) => handleIdChange(e.target.value)}
                disabled={isEdit}
                placeholder="e.g. MATH09_C"
                className="flex-1 min-w-0 bg-slate-50 disabled:bg-slate-100/70 border border-slate-300 rounded-xl px-3 py-2 text-xs font-mono font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
              />
              {!isEdit && !idAutoGenerated && (
                <button
                  type="button"
                  onClick={resetAutoId}
                  title="Re-generate ID"
                  className="px-2 py-1.5 rounded-lg border border-indigo-200 bg-indigo-50 text-indigo-700 hover:bg-indigo-100 transition-colors cursor-pointer shrink-0"
                >
                  <Wand2 className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
            {isEdit ? (
              <span className="text-[10px] text-slate-400 mt-0.5 block">
                ID cannot be changed once created.
              </span>
            ) : (
              <span className="text-[10px] text-slate-400 mt-0.5 block">
                Auto-generated from Subject Name + Grade + Section. You can override it.
              </span>
            )}
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
            {/* Weekly Periods */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Weekly Periods <span className="text-rose-500">*</span>
              </label>
              <input
                type="number"
                min={1}
                max={20}
                value={weeklyPeriods}
                onChange={(e) => setWeeklyPeriods(Number(e.target.value))}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                required
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">
                Classes per week (typical: 5–7)
              </span>
            </div>

            {/* Assigned Teacher */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Assigned Teacher <span className="text-rose-500">*</span>
              </label>
              <select
                value={teacherId}
                onChange={(e) => setTeacherId(e.target.value)}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                required
              >
                <option value="" disabled>
                  Select Teacher
                </option>
                {teachers.map((t) => (
                  <option key={t.teacher_id} value={t.teacher_id}>
                    {t.teacher_name} ({t.department || "Academic"})
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* Lab Requirement */}
          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
            <label className="flex items-center gap-3 cursor-pointer select-none">
              <input
                type="checkbox"
                checked={labRequired}
                onChange={(e) => setLabRequired(e.target.checked)}
                className="w-4 h-4 rounded text-indigo-600 focus:ring-indigo-500 border-slate-300"
              />
              <div className="flex items-center gap-2">
                <FlaskConical className="w-4 h-4 text-purple-600" />
                <div>
                  <span className="text-xs font-bold text-slate-800">
                    Requires Specialized Laboratory
                  </span>
                  <p className="text-[11px] text-slate-500">
                    Must be scheduled in a room marked as a Lab (Science Lab, Computer Lab, etc.)
                  </p>
                </div>
              </div>
            </label>
          </div>

          {/* Footer Actions */}
          <div className="pt-3 border-t border-slate-100 flex items-center justify-end gap-2.5 shrink-0">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="px-4 py-2 rounded-xl border border-slate-200 text-xs font-semibold text-slate-700 hover:bg-slate-50 transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="inline-flex items-center gap-2 px-5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-700 disabled:opacity-60 text-white text-xs font-semibold shadow-xs transition-all cursor-pointer"
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  <span>Saving...</span>
                </>
              ) : (
                <span>{isEdit ? "Update Course" : "Create Course"}</span>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
