import React, { useState, useEffect } from "react";
import { StudentGroup, Course, Teacher, Room } from "../../types";
import { GraduationCap, X, Loader2, AlertCircle, Check, Wand2, Copy, Search } from "lucide-react";

interface GroupModalProps {
  isOpen: boolean;
  group?: StudentGroup | null;
  existingGroupIds: string[];
  courses: Course[];
  teachers: Teacher[];
  rooms: Room[];
  groups: StudentGroup[]; // for copy-from
  onSave: (data: {
    group_id: string;
    group_name: string;
    student_count: number;
    enrolled_courses: string[];
    grade_level?: string;
    homeroom_teacher?: string;
    homeroom_room_id?: string;
  }) => Promise<void>;
  onClose: () => void;
}

// Extract grade number from group name: "Grade 9 - Section A" → "9"
function extractGrade(name: string): string {
  const m = name.match(/(\d+)/);
  return m ? m[1] : "";
}

// Extract section letter: "Grade 9 - Section A" or "Grade 9-B" → "A" or "B"
function extractSection(name: string): string {
  // Match "Section X" pattern
  const sectionMatch = name.match(/section\s+([A-Za-z])/i);
  if (sectionMatch) return sectionMatch[1].toUpperCase();
  // Match trailing "-X" or " X" single letter
  const trailingMatch = name.match(/[-\s]([A-Za-z])$/);
  if (trailingMatch) return trailingMatch[1].toUpperCase();
  // Match word after last space
  const wordMatch = name.trim().match(/\s([A-Za-z]{1,2})$/);
  if (wordMatch) return wordMatch[1].toUpperCase();
  return "";
}

// Auto-generate group ID
function generateGroupId(name: string, existingIds: string[]): string {
  const grade = extractGrade(name);
  const section = extractSection(name);

  if (!grade) return "";

  let base = `G${grade}`;
  if (section) base += `-${section}`;

  const upper = existingIds.map((id) => id.toUpperCase());
  if (!upper.includes(base.toUpperCase())) return base;

  let n = 2;
  while (upper.includes(`${base}-${n}`.toUpperCase())) n++;
  return `${base}-${n}`;
}

export const GroupModal: React.FC<GroupModalProps> = ({
  isOpen,
  group,
  existingGroupIds,
  courses,
  teachers,
  rooms,
  groups,
  onSave,
  onClose,
}) => {
  const isEdit = !!group;

  const [groupId, setGroupId] = useState("");
  const [idAutoGenerated, setIdAutoGenerated] = useState(true);
  const [groupName, setGroupName] = useState("");
  const [studentCount, setStudentCount] = useState(30);
  const [gradeLevel, setGradeLevel] = useState("9");
  const [homeroomTeacher, setHomeroomTeacher] = useState("");
  const [homeroomRoomId, setHomeroomRoomId] = useState("");
  const [selectedCourses, setSelectedCourses] = useState<string[]>([]);
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [courseSearch, setCourseSearch] = useState("");
  const [copyFromGroupId, setCopyFromGroupId] = useState("");

  useEffect(() => {
    if (group) {
      setGroupId(group.group_id);
      setIdAutoGenerated(false);
      setGroupName(group.group_name);
      setStudentCount(group.student_count || 30);
      setGradeLevel(group.grade_level || "9");
      setHomeroomTeacher(group.homeroom_teacher || "");
      setHomeroomRoomId(group.homeroom_room_id || "");
      setSelectedCourses(group.enrolled_courses || []);
    } else {
      setGroupId("");
      setIdAutoGenerated(true);
      setGroupName("");
      setStudentCount(30);
      setGradeLevel("9");
      setHomeroomTeacher("");
      setHomeroomRoomId(rooms[0]?.room_id || "");
      setSelectedCourses([]);
      setCopyFromGroupId("");
    }
    setCourseSearch("");
    setError(null);
  }, [group, teachers, rooms, isOpen]);

  const handleNameChange = (name: string) => {
    setGroupName(name);
    // Auto-extract grade level
    const grade = extractGrade(name);
    if (grade) setGradeLevel(grade);
    // Auto-generate ID
    if (!isEdit && idAutoGenerated) {
      const newId = generateGroupId(name, existingGroupIds);
      setGroupId(newId);
    }
  };

  const handleIdChange = (val: string) => {
    setGroupId(val);
    setIdAutoGenerated(false);
  };

  const resetAutoId = () => {
    setIdAutoGenerated(true);
    setGroupId(generateGroupId(groupName, existingGroupIds));
  };

  // Copy from an existing class
  const handleCopyFromGroup = (sourceGroupId: string) => {
    setCopyFromGroupId(sourceGroupId);
    const src = groups.find((g) => g.group_id === sourceGroupId);
    if (!src) return;
    setStudentCount(src.student_count);
    setHomeroomTeacher(src.homeroom_teacher || "");
    setHomeroomRoomId(src.homeroom_room_id || "");
    setSelectedCourses([...src.enrolled_courses]);
    // Keep grade level auto-extracted from current name
  };

  const toggleCourse = (courseId: string) => {
    setSelectedCourses((prev) =>
      prev.includes(courseId) ? prev.filter((id) => id !== courseId) : [...prev, courseId]
    );
  };

  const totalPeriodsScheduled = courses
    .filter((c) => selectedCourses.includes(c.course_id))
    .reduce((sum, c) => sum + c.weekly_periods, 0);

  // Filter courses by search
  const filteredCourses = courses.filter(
    (c) =>
      courseSearch === "" ||
      c.course_name.toLowerCase().includes(courseSearch.toLowerCase()) ||
      c.course_id.toLowerCase().includes(courseSearch.toLowerCase()) ||
      (c.department && c.department.toLowerCase().includes(courseSearch.toLowerCase()))
  );

  const sourceGroupForPreview = groups.find((g) => g.group_id === copyFromGroupId);

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    const cleanId = groupId.trim().toUpperCase();
    const cleanName = groupName.trim();

    if (!cleanId) {
      setError("Class Code / Section ID is required. It auto-generates from the class name.");
      return;
    }
    if (!cleanName) {
      setError("Class Name is required.");
      return;
    }
    if (!isEdit && existingGroupIds.map((id) => id.toUpperCase()).includes(cleanId)) {
      setError(`Class ID '${cleanId}' is already in use.`);
      return;
    }
    if (studentCount < 1 || studentCount > 200) {
      setError("Class student count must be between 1 and 200.");
      return;
    }
    if (selectedCourses.length === 0) {
      setError("Please enroll at least one course for this class.");
      return;
    }

    setIsSubmitting(true);
    try {
      await onSave({
        group_id: cleanId,
        group_name: cleanName,
        student_count: Number(studentCount),
        grade_level: gradeLevel.trim() || "9",
        homeroom_teacher: homeroomTeacher.trim() || undefined,
        homeroom_room_id: homeroomRoomId.trim() || undefined,
        enrolled_courses: selectedCourses,
      });
      onClose();
    } catch (err: any) {
      setError(err.message || "Failed to save class group.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-xs p-4 animate-in fade-in duration-150">
      <div className="bg-white rounded-2xl border border-slate-200 max-w-xl w-full p-6 text-slate-900 shadow-2xl flex flex-col max-h-[95vh]">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-100 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-50 border border-amber-100 text-amber-600 flex items-center justify-center shrink-0">
              <GraduationCap className="w-5 h-5 stroke-[2.2]" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">
                {isEdit ? "Edit School Class" : "Add New School Class"}
              </h3>
              <p className="text-xs text-slate-500">
                {isEdit
                  ? "Update class details and enrolled subjects"
                  : "Type class name — ID auto-generates. Copy subjects from an existing class."}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors disabled:opacity-40 cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body (Scrollable) */}
        <form onSubmit={handleSubmit} className="py-4 space-y-4 overflow-y-auto flex-1 pr-1">
          {error && (
            <div className="p-3 rounded-xl bg-rose-50 border border-rose-200 flex items-start gap-2.5 text-xs text-rose-800">
              <AlertCircle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          {/* Copy from existing class (Add mode only) */}
          {!isEdit && groups.length > 0 && (
            <div className="p-3 rounded-xl bg-amber-50 border border-amber-200">
              <label className="flex items-center gap-1.5 text-xs font-semibold text-amber-800 mb-2">
                <Copy className="w-3.5 h-3.5" />
                Copy curriculum from an existing class
              </label>
              <select
                value={copyFromGroupId}
                onChange={(e) => handleCopyFromGroup(e.target.value)}
                className="w-full bg-white border border-amber-200 rounded-lg px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500"
              >
                <option value="">(Select a class to copy its subjects)</option>
                {groups.map((g) => (
                  <option key={g.group_id} value={g.group_id}>
                    {g.group_name} — {g.enrolled_courses.length} subjects ({g.group_id})
                  </option>
                ))}
              </select>
              {sourceGroupForPreview && (
                <div className="mt-2 p-2 bg-white rounded-lg border border-amber-100">
                  <p className="text-[10px] font-semibold text-amber-700 mb-1">
                    Will copy {sourceGroupForPreview.enrolled_courses.length} enrolled subjects:
                  </p>
                  <div className="flex flex-wrap gap-1">
                    {sourceGroupForPreview.enrolled_courses.map((cid) => {
                      const c = courses.find((x) => x.course_id === cid);
                      return (
                        <span
                          key={cid}
                          className="px-1.5 py-0.5 rounded bg-amber-100 text-amber-800 text-[10px] font-mono font-semibold"
                          title={c?.course_name}
                        >
                          {cid}
                        </span>
                      );
                    })}
                  </div>
                  <p className="text-[10px] text-amber-600 mt-1.5">
                    ⚠️ The same course IDs are enrolled — they will be shared with this class. If you want separate course IDs per section, add the courses first, then enroll them here.
                  </p>
                </div>
              )}
            </div>
          )}

          {/* Class Section Name — FIRST to drive auto-ID */}
          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Class Section Name <span className="text-rose-500">*</span>
            </label>
            <input
              type="text"
              value={groupName}
              onChange={(e) => handleNameChange(e.target.value)}
              placeholder="e.g. Grade 9 - Section C"
              className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500"
              required
              autoFocus={!isEdit}
            />
            {!isEdit && (
              <p className="text-[10px] text-slate-400 mt-0.5">
                Type e.g. "Grade 9 - Section C" — Class ID and Grade Level auto-extract.
              </p>
            )}
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
            {/* Class ID (auto-generated) */}
            <div>
              <label className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 mb-1">
                Class ID <span className="text-rose-500">*</span>
                {!isEdit && idAutoGenerated && (
                  <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full bg-amber-50 border border-amber-200 text-amber-700 text-[9px] font-bold">
                    <Wand2 className="w-2.5 h-2.5" /> Auto
                  </span>
                )}
              </label>
              <div className="flex gap-1.5">
                <input
                  type="text"
                  value={groupId}
                  onChange={(e) => handleIdChange(e.target.value)}
                  disabled={isEdit}
                  placeholder="e.g. G9-C"
                  className="flex-1 min-w-0 bg-slate-50 disabled:bg-slate-100/70 border border-slate-300 rounded-xl px-3 py-2 text-xs font-mono font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500"
                />
                {!isEdit && !idAutoGenerated && (
                  <button
                    type="button"
                    onClick={resetAutoId}
                    title="Re-generate ID"
                    className="px-2 py-1.5 rounded-lg border border-amber-200 bg-amber-50 text-amber-700 hover:bg-amber-100 transition-colors cursor-pointer shrink-0"
                  >
                    <Wand2 className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
              {isEdit && (
                <span className="text-[10px] text-slate-400 mt-0.5 block">
                  ID cannot be changed once created.
                </span>
              )}
            </div>

            {/* Grade Level */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Grade / Year
              </label>
              <input
                type="text"
                value={gradeLevel}
                onChange={(e) => setGradeLevel(e.target.value)}
                placeholder="e.g. 9 or 10"
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500"
              />
              <span className="text-[10px] text-slate-400 mt-0.5 block">Auto-extracted from class name</span>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3.5">
            {/* Student Count */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Students <span className="text-rose-500">*</span>
              </label>
              <input
                type="number"
                min={1}
                max={200}
                value={studentCount}
                onChange={(e) => setStudentCount(Number(e.target.value))}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500"
                required
              />
            </div>

            {/* Homeroom Teacher */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Homeroom Teacher
              </label>
              <select
                value={homeroomTeacher}
                onChange={(e) => setHomeroomTeacher(e.target.value)}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500"
              >
                <option value="">(None)</option>
                {teachers.map((t) => (
                  <option key={t.teacher_id} value={t.teacher_name}>
                    {t.teacher_name}
                  </option>
                ))}
              </select>
            </div>

            {/* Base Room */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Base Classroom
              </label>
              <select
                value={homeroomRoomId}
                onChange={(e) => setHomeroomRoomId(e.target.value)}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500"
              >
                <option value="">(None)</option>
                {rooms.map((r) => (
                  <option key={r.room_id} value={r.room_id}>
                    {r.room_name || r.room_id} ({r.room_capacity} seats)
                  </option>
                ))}
              </select>
            </div>
          </div>

          {/* Enrolled Courses Selector */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="block text-xs font-semibold text-slate-700">
                Enrolled Subjects <span className="text-rose-500">*</span>
              </label>
              <div className="flex items-center gap-2">
                <span
                  className={`text-xs font-mono font-bold px-2 py-0.5 rounded-full border ${
                    totalPeriodsScheduled > 40
                      ? "bg-rose-50 text-rose-700 border-rose-200"
                      : totalPeriodsScheduled > 35
                      ? "bg-amber-50 text-amber-700 border-amber-200"
                      : "bg-indigo-50 text-indigo-700 border-indigo-100"
                  }`}
                >
                  {selectedCourses.length} subjects • {totalPeriodsScheduled}/40 periods
                </span>
                {selectedCourses.length > 0 && (
                  <button
                    type="button"
                    onClick={() => setSelectedCourses([])}
                    className="text-[10px] text-rose-500 hover:text-rose-700 font-semibold cursor-pointer"
                  >
                    Clear
                  </button>
                )}
              </div>
            </div>

            {/* Search Filter */}
            <div className="relative mb-1.5">
              <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-slate-400" />
              <input
                type="text"
                value={courseSearch}
                onChange={(e) => setCourseSearch(e.target.value)}
                placeholder="Search subjects by name, code, or department..."
                className="w-full pl-7 pr-3 py-1.5 bg-slate-50 border border-slate-200 rounded-lg text-xs text-slate-700 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-400"
              />
            </div>

            <div className="border border-slate-200 rounded-xl max-h-52 overflow-y-auto p-2 space-y-1 bg-slate-50/50">
              {filteredCourses.length === 0 ? (
                <p className="text-xs text-slate-400 text-center py-4">
                  No subjects match your search.
                </p>
              ) : (
                filteredCourses.map((c) => {
                  const isChecked = selectedCourses.includes(c.course_id);
                  return (
                    <div
                      key={c.course_id}
                      onClick={() => toggleCourse(c.course_id)}
                      className={`flex items-center justify-between p-2 rounded-lg cursor-pointer text-xs transition-colors border ${
                        isChecked
                          ? "bg-indigo-50/80 border-indigo-200 text-indigo-950 font-medium"
                          : "bg-white border-slate-200 hover:bg-slate-100 text-slate-700"
                      }`}
                    >
                      <div className="flex items-center gap-2.5">
                        <div
                          className={`w-4 h-4 rounded border flex items-center justify-center shrink-0 ${
                            isChecked
                              ? "bg-indigo-600 border-indigo-600 text-white"
                              : "border-slate-300 bg-white"
                          }`}
                        >
                          {isChecked && <Check className="w-3 h-3 stroke-[3]" />}
                        </div>
                        <div>
                          <span className="font-bold mr-1.5 font-mono text-[11px]">{c.course_id}</span>
                          <span>{c.course_name}</span>
                          {c.department && (
                            <span className="ml-1.5 text-slate-400">· {c.department}</span>
                          )}
                        </div>
                      </div>
                      <span className="px-1.5 py-0.5 rounded bg-white text-slate-600 border border-slate-200 text-[10px] font-semibold shrink-0">
                        {c.weekly_periods}p/wk
                      </span>
                    </div>
                  );
                })
              )}
            </div>
            {totalPeriodsScheduled > 40 && (
              <p className="text-[10px] text-rose-600 mt-1 font-semibold">
                ⚠️ {totalPeriodsScheduled} periods exceeds the 40-period weekly limit. Remove some subjects.
              </p>
            )}
          </div>

          {/* Footer Actions */}
          <div className="pt-3 border-t border-slate-100 flex items-center justify-end gap-2.5 shrink-0">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="px-4 py-2 rounded-xl border border-slate-200 text-xs font-semibold text-slate-700 hover:bg-slate-50 transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="inline-flex items-center gap-2 px-5 py-2 rounded-xl bg-amber-600 hover:bg-amber-700 disabled:opacity-60 text-white text-xs font-semibold shadow-xs transition-all cursor-pointer"
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  <span>Saving...</span>
                </>
              ) : (
                <span>{isEdit ? "Update Class" : "Create Class"}</span>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
