import React, { useState, useEffect } from "react";
import { Room } from "../../types";
import { Building2, X, Loader2, FlaskConical, AlertCircle, Wand2 } from "lucide-react";

interface RoomModalProps {
  isOpen: boolean;
  room?: Room | null;
  existingRoomIds: string[];
  existingRooms: Room[];
  onSave: (data: {
    room_id: string;
    room_capacity: number;
    is_lab: boolean;
    room_name?: string;
    room_type?: "Classroom" | "Science Lab" | "Computer Lab" | "Art Studio" | "Sports Ground" | "Library";
  }) => Promise<void>;
  onClose: () => void;
}

const ROOM_TYPES: Array<"Classroom" | "Science Lab" | "Computer Lab" | "Art Studio" | "Sports Ground" | "Library"> = [
  "Classroom",
  "Science Lab",
  "Computer Lab",
  "Art Studio",
  "Sports Ground",
  "Library",
];

// Auto-generate room ID based on type and existing rooms of that type
function generateRoomId(
  type: string,
  existingRooms: Room[],
  existingRoomIds: string[]
): string {
  const prefixMap: Record<string, string> = {
    "Classroom": "RM",
    "Science Lab": "SCI-LAB",
    "Computer Lab": "COMP-LAB",
    "Art Studio": "ART-STUDIO",
    "Sports Ground": "GYM-FIELD",
    "Library": "LIBRARY",
  };

  const prefix = prefixMap[type] || "RM";
  const allIds = existingRoomIds.map((id) => id.toUpperCase());

  if (type === "Classroom") {
    // Use RM-101, RM-102, etc.
    const classrooms = existingRooms.filter(
      (r) => !r.room_type || r.room_type === "Classroom"
    );
    let num = 101 + classrooms.length;
    while (allIds.includes(`RM-${num}`)) num++;
    return `RM-${num}`;
  } else {
    // SCI-LAB, SCI-LAB-2, SCI-LAB-3, etc.
    if (!allIds.includes(prefix)) return prefix;
    let n = 2;
    while (allIds.includes(`${prefix}-${n}`)) n++;
    return `${prefix}-${n}`;
  }
}

// Auto-suggest room name based on type and count
function suggestRoomName(type: string, existingRooms: Room[]): string {
  const sameType = existingRooms.filter((r) => r.room_type === type);
  const count = sameType.length + 1;

  const nameMap: Record<string, string[]> = {
    "Classroom": ["Class Homeroom", "General Classroom", "Academic Classroom"],
    "Science Lab": ["Composite Science Lab", "Physics & Chemistry Lab", "Biology Lab"],
    "Computer Lab": ["Computer & Robotics Lab", "IT & Programming Lab", "Digital Learning Lab"],
    "Art Studio": ["Visual Arts Workshop", "Creative Arts Studio", "Fine Arts Room"],
    "Sports Ground": ["Sports Complex & Field", "Gymnasium & Field", "Sports Hall"],
    "Library": ["Central School Library", "Resource & Reading Room", "Media Center"],
  };

  const suggestions = nameMap[type] || ["General Room"];
  return suggestions[Math.min(count - 1, suggestions.length - 1)];
}

export const RoomModal: React.FC<RoomModalProps> = ({
  isOpen,
  room,
  existingRoomIds,
  existingRooms,
  onSave,
  onClose,
}) => {
  const isEdit = !!room;

  const [roomId, setRoomId] = useState("");
  const [idAutoGenerated, setIdAutoGenerated] = useState(true);
  const [roomName, setRoomName] = useState("");
  const [nameAutoGenerated, setNameAutoGenerated] = useState(true);
  const [roomType, setRoomType] = useState<"Classroom" | "Science Lab" | "Computer Lab" | "Art Studio" | "Sports Ground" | "Library">("Classroom");
  const [roomCapacity, setRoomCapacity] = useState(35);
  const [isLab, setIsLab] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    if (room) {
      setRoomId(room.room_id);
      setIdAutoGenerated(false);
      setRoomName(room.room_name || "");
      setNameAutoGenerated(false);
      setRoomType(room.room_type || (room.is_lab ? "Science Lab" : "Classroom"));
      setRoomCapacity(room.room_capacity || 35);
      setIsLab(room.is_lab);
    } else {
      const defaultType = "Classroom";
      const autoId = generateRoomId(defaultType, existingRooms, existingRoomIds);
      const autoName = suggestRoomName(defaultType, existingRooms);
      setRoomId(autoId);
      setIdAutoGenerated(true);
      setRoomName(autoName);
      setNameAutoGenerated(true);
      setRoomType(defaultType);
      setRoomCapacity(35);
      setIsLab(false);
    }
    setError(null);
  }, [room, isOpen, existingRooms, existingRoomIds]);

  const handleTypeChange = (val: typeof roomType) => {
    setRoomType(val);
    if (val === "Science Lab" || val === "Computer Lab") {
      setIsLab(true);
    } else {
      setIsLab(false);
    }
    // Auto-update ID and Name if still in auto mode
    if (!isEdit && idAutoGenerated) {
      setRoomId(generateRoomId(val, existingRooms, existingRoomIds));
    }
    if (!isEdit && nameAutoGenerated) {
      setRoomName(suggestRoomName(val, existingRooms));
    }
  };

  const handleIdChange = (val: string) => {
    setRoomId(val);
    setIdAutoGenerated(false);
  };

  const handleNameChange = (val: string) => {
    setRoomName(val);
    setNameAutoGenerated(false);
  };

  const resetAutoId = () => {
    setIdAutoGenerated(true);
    setRoomId(generateRoomId(roomType, existingRooms, existingRoomIds));
  };

  const resetAutoName = () => {
    setNameAutoGenerated(true);
    setRoomName(suggestRoomName(roomType, existingRooms));
  };

  if (!isOpen) return null;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    const cleanId = roomId.trim().toUpperCase();
    const cleanName = roomName.trim();

    if (!cleanId) {
      setError("Facility ID (Room ID) is required.");
      return;
    }
    if (!cleanName) {
      setError("Facility Name is required.");
      return;
    }
    if (!isEdit && existingRoomIds.map((id) => id.toUpperCase()).includes(cleanId)) {
      setError(`Room ID '${cleanId}' is already in use.`);
      return;
    }
    if (roomCapacity < 1 || roomCapacity > 500) {
      setError("Student seating capacity must be between 1 and 500.");
      return;
    }

    setIsSubmitting(true);
    try {
      await onSave({
        room_id: cleanId,
        room_name: cleanName,
        room_capacity: Number(roomCapacity),
        room_type: roomType,
        is_lab: isLab,
      });
      onClose();
    } catch (err: any) {
      setError(err.message || "Failed to save room record.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-xs p-4 animate-in fade-in duration-150">
      <div className="bg-white rounded-2xl border border-slate-200 max-w-lg w-full p-6 text-slate-900 shadow-2xl flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-100">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-violet-50 border border-violet-100 text-violet-600 flex items-center justify-center shrink-0">
              <Building2 className="w-5 h-5 stroke-[2.2]" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">
                {isEdit ? "Edit Facility / Room" : "Add Campus Facility"}
              </h3>
              <p className="text-xs text-slate-500">
                {isEdit ? "Update room details" : "Select type — Room ID and name are auto-suggested"}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors disabled:opacity-40 cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="py-4 space-y-4">
          {error && (
            <div className="p-3 rounded-xl bg-rose-50 border border-rose-200 flex items-start gap-2.5 text-xs text-rose-800">
              <AlertCircle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          {/* Category / Type — FIRST so auto-ID triggers */}
          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Facility Type <span className="text-rose-500">*</span>
            </label>
            <div className="grid grid-cols-3 gap-1.5">
              {ROOM_TYPES.map((type) => (
                <button
                  key={type}
                  type="button"
                  onClick={() => handleTypeChange(type)}
                  className={`px-2 py-2 rounded-lg text-[11px] font-semibold border transition-all cursor-pointer text-center ${
                    roomType === type
                      ? "bg-violet-600 border-violet-600 text-white shadow-xs"
                      : "bg-slate-50 border-slate-200 text-slate-700 hover:border-violet-300 hover:bg-violet-50"
                  }`}
                >
                  {type}
                </button>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
            {/* Room ID (auto-generated) */}
            <div>
              <label className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 mb-1">
                Room ID <span className="text-rose-500">*</span>
                {!isEdit && idAutoGenerated && (
                  <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full bg-violet-50 border border-violet-200 text-violet-700 text-[9px] font-bold">
                    <Wand2 className="w-2.5 h-2.5" /> Auto
                  </span>
                )}
              </label>
              <div className="flex gap-1.5">
                <input
                  type="text"
                  value={roomId}
                  onChange={(e) => handleIdChange(e.target.value)}
                  disabled={isEdit}
                  placeholder="e.g. RM-202"
                  className="flex-1 min-w-0 bg-slate-50 disabled:bg-slate-100/70 border border-slate-300 rounded-xl px-3 py-2 text-xs font-mono font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-violet-500/20 focus:border-violet-500"
                />
                {!isEdit && !idAutoGenerated && (
                  <button
                    type="button"
                    onClick={resetAutoId}
                    title="Re-generate ID"
                    className="px-2 py-1.5 rounded-lg border border-violet-200 bg-violet-50 text-violet-700 hover:bg-violet-100 transition-colors cursor-pointer shrink-0"
                  >
                    <Wand2 className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
              {isEdit && (
                <span className="text-[10px] text-slate-400 mt-0.5 block">
                  ID cannot be changed once created.
                </span>
              )}
            </div>

            {/* Capacity */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Seating Capacity <span className="text-rose-500">*</span>
              </label>
              <input
                type="number"
                min={1}
                max={500}
                value={roomCapacity}
                onChange={(e) => setRoomCapacity(Number(e.target.value))}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-violet-500/20 focus:border-violet-500"
                required
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">
                Must be ≥ class student count
              </span>
            </div>
          </div>

          {/* Facility Name (auto-suggested) */}
          <div>
            <label className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 mb-1">
              Facility Name <span className="text-rose-500">*</span>
              {!isEdit && nameAutoGenerated && (
                <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full bg-violet-50 border border-violet-200 text-violet-700 text-[9px] font-bold">
                  <Wand2 className="w-2.5 h-2.5" /> Suggested
                </span>
              )}
            </label>
            <div className="flex gap-1.5">
              <input
                type="text"
                value={roomName}
                onChange={(e) => handleNameChange(e.target.value)}
                placeholder="e.g. Grade 9-A Homeroom"
                className="flex-1 min-w-0 bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-violet-500/20 focus:border-violet-500"
                required
              />
              {!isEdit && !nameAutoGenerated && (
                <button
                  type="button"
                  onClick={resetAutoName}
                  title="Re-suggest name"
                  className="px-2 py-1.5 rounded-lg border border-violet-200 bg-violet-50 text-violet-700 hover:bg-violet-100 transition-colors cursor-pointer shrink-0"
                >
                  <Wand2 className="w-3.5 h-3.5" />
                </button>
              )}
            </div>
          </div>

          {/* Lab Flag */}
          <div className="p-3.5 rounded-xl bg-slate-50 border border-slate-200">
            <label className="flex items-center gap-3 cursor-pointer select-none">
              <input
                type="checkbox"
                checked={isLab}
                onChange={(e) => setIsLab(e.target.checked)}
                className="w-4 h-4 rounded text-violet-600 focus:ring-violet-500 border-slate-300"
              />
              <div className="flex items-center gap-2">
                <FlaskConical className="w-4 h-4 text-violet-600" />
                <div>
                  <span className="text-xs font-bold text-slate-800">
                    Specialized Lab / Workshop
                  </span>
                  <p className="text-[11px] text-slate-500">
                    Auto-enabled for Science Lab and Computer Lab types. Required for lab subjects.
                  </p>
                </div>
              </div>
            </label>
          </div>

          {/* Footer Actions */}
          <div className="pt-3 border-t border-slate-100 flex items-center justify-end gap-2.5">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="px-4 py-2 rounded-xl border border-slate-200 text-xs font-semibold text-slate-700 hover:bg-slate-50 transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="inline-flex items-center gap-2 px-5 py-2 rounded-xl bg-violet-600 hover:bg-violet-700 disabled:opacity-60 text-white text-xs font-semibold shadow-xs transition-all cursor-pointer"
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  <span>Saving...</span>
                </>
              ) : (
                <span>{isEdit ? "Update Facility" : "Create Facility"}</span>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
