import React, { useState, useEffect, useCallback } from "react";
import { Teacher } from "../../types";
import { Users, X, Loader2, AlertCircle, Wand2 } from "lucide-react";

interface TeacherModalProps {
  isOpen: boolean;
  teacher?: Teacher | null;
  existingTeacherIds: string[];
  onSave: (data: {
    teacher_id: string;
    teacher_name: string;
    max_hours_per_day: number;
    unavailable_times: string;
    department?: string;
    homeroom_class?: string;
    email?: string;
  }) => Promise<void>;
  onClose: () => void;
}

const DEPARTMENTS = [
  "Mathematics",
  "Science",
  "English",
  "Social Science",
  "Hindi",
  "Technology",
  "Physical Education",
  "Fine Arts",
  "Resource",
  "Academic",
  "General",
];

const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri"];
const PERIODS = [1, 2, 3, 4, 5, 6, 7, 8];

// Generate teacher ID from full name: "Dr. Rohit Verma" → "T_ROHIT_VERMA"
function generateTeacherId(name: string): string {
  const prefixes = /^(dr\.?|mr\.?|mrs\.?|ms\.?|prof\.?|sir|shri|smt\.?)\s+/i;
  const cleaned = name.trim().replace(prefixes, "");
  const parts = cleaned
    .split(/\s+/)
    .map((w) => w.replace(/[^a-zA-Z]/g, "").toUpperCase())
    .filter(Boolean);
  if (parts.length === 0) return "";
  return "T_" + parts.join("_");
}

// Parse "Mon:1, Fri:7" into a Set of "Mon:1" keys
function parseSlots(val: string): Set<string> {
  const result = new Set<string>();
  if (!val) return result;
  val.split(",").forEach((tok) => {
    const m = tok.trim().match(/^([A-Za-z]+)[:\-](\d+)$/);
    if (m) {
      const day = m[1].charAt(0).toUpperCase() + m[1].slice(1, 3).toLowerCase();
      const p = parseInt(m[2]);
      if (DAYS.includes(day) && p >= 1 && p <= 8) {
        result.add(`${day}:${p}`);
      }
    }
  });
  return result;
}

function slotsToString(slots: Set<string>): string {
  return Array.from(slots)
    .sort((a, b) => {
      const [da, pa] = a.split(":");
      const [db, pb] = b.split(":");
      return DAYS.indexOf(da) - DAYS.indexOf(db) || parseInt(pa) - parseInt(pb);
    })
    .join(", ");
}

export const TeacherModal: React.FC<TeacherModalProps> = ({
  isOpen,
  teacher,
  existingTeacherIds,
  onSave,
  onClose,
}) => {
  const isEdit = !!teacher;

  const [teacherId, setTeacherId] = useState("");
  const [idAutoGenerated, setIdAutoGenerated] = useState(true);
  const [teacherName, setTeacherName] = useState("");
  const [department, setDepartment] = useState("General");
  const [maxHoursPerDay, setMaxHoursPerDay] = useState(5);
  const [unavailableSlots, setUnavailableSlots] = useState<Set<string>>(new Set());
  const [homeroomClass, setHomeroomClass] = useState("");
  const [email, setEmail] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    if (teacher) {
      setTeacherId(teacher.teacher_id);
      setIdAutoGenerated(false);
      setTeacherName(teacher.teacher_name);
      setDepartment(teacher.department || "General");
      setMaxHoursPerDay(teacher.max_hours_per_day || 5);
      setUnavailableSlots(parseSlots(teacher.unavailable_times || ""));
      setHomeroomClass(teacher.homeroom_class || "");
      setEmail(teacher.email || "");
    } else {
      setTeacherId("");
      setIdAutoGenerated(true);
      setTeacherName("");
      setDepartment("General");
      setMaxHoursPerDay(5);
      setUnavailableSlots(new Set());
      setHomeroomClass("");
      setEmail("");
    }
    setError(null);
  }, [teacher, isOpen]);

  // Auto-generate ID from name (only in add mode and when auto mode is on)
  const handleNameChange = useCallback(
    (name: string) => {
      setTeacherName(name);
      if (!isEdit && idAutoGenerated) {
        const generated = generateTeacherId(name);
        setTeacherId(generated);
      }
    },
    [isEdit, idAutoGenerated]
  );

  const handleIdChange = (val: string) => {
    setTeacherId(val);
    setIdAutoGenerated(false); // user is manually overriding
  };

  const resetAutoId = () => {
    setIdAutoGenerated(true);
    setTeacherId(generateTeacherId(teacherName));
  };

  const toggleSlot = (day: string, period: number) => {
    const key = `${day}:${period}`;
    setUnavailableSlots((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  };

  if (!isOpen) return null;

  const unavailableTimesString = slotsToString(unavailableSlots);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);

    const cleanId = teacherId.trim().toUpperCase();
    const cleanName = teacherName.trim();

    if (!cleanId) {
      setError("Teacher ID is required. It will auto-fill when you type a name.");
      return;
    }
    if (!cleanName) {
      setError("Teacher Full Name is required.");
      return;
    }
    if (!isEdit && existingTeacherIds.map((id) => id.toUpperCase()).includes(cleanId)) {
      setError(`Teacher ID '${cleanId}' is already in use. The ID was adjusted — please check.`);
      return;
    }
    if (maxHoursPerDay < 1 || maxHoursPerDay > 8) {
      setError("Daily workload cap must be between 1 and 8 periods.");
      return;
    }

    setIsSubmitting(true);
    try {
      await onSave({
        teacher_id: cleanId,
        teacher_name: cleanName,
        max_hours_per_day: Number(maxHoursPerDay),
        unavailable_times: unavailableTimesString,
        department: department.trim() || "General",
        homeroom_class: homeroomClass.trim() || undefined,
        email: email.trim() || undefined,
      });
      onClose();
    } catch (err: any) {
      setError(err.message || "Failed to save teacher record.");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-xs p-4 animate-in fade-in duration-150">
      <div className="bg-white rounded-2xl border border-slate-200 max-w-xl w-full p-6 text-slate-900 shadow-2xl flex flex-col max-h-[95vh]">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-100 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-50 border border-emerald-100 text-emerald-600 flex items-center justify-center shrink-0">
              <Users className="w-5 h-5 stroke-[2.2]" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">
                {isEdit ? "Edit Teaching Faculty" : "Add Teaching Faculty"}
              </h3>
              <p className="text-xs text-slate-500">
                {isEdit ? "Update faculty details and constraints" : "Type the teacher's name — ID is generated automatically"}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition-colors disabled:opacity-40 cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Form Body */}
        <form onSubmit={handleSubmit} className="py-4 space-y-4 overflow-y-auto flex-1 pr-1">
          {error && (
            <div className="p-3 rounded-xl bg-rose-50 border border-rose-200 flex items-start gap-2.5 text-xs text-rose-800">
              <AlertCircle className="w-4 h-4 text-rose-600 shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          {/* Full Name — FIRST so auto-ID triggers */}
          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Full Name <span className="text-rose-500">*</span>
            </label>
            <input
              type="text"
              value={teacherName}
              onChange={(e) => handleNameChange(e.target.value)}
              placeholder="e.g. Dr. Rohit Verma"
              className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs font-semibold text-slate-900 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500"
              required
              autoFocus={!isEdit}
            />
            {!isEdit && (
              <p className="text-[10px] text-slate-400 mt-0.5">
                Start typing a name — the Teacher ID below will be auto-generated.
              </p>
            )}
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
            {/* Teacher ID */}
            <div>
              <label className="flex items-center gap-1.5 text-xs font-semibold text-slate-700 mb-1">
                Teacher ID <span className="text-rose-500">*</span>
                {!isEdit && idAutoGenerated && (
                  <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-700 text-[9px] font-bold">
                    <Wand2 className="w-2.5 h-2.5" /> Auto
                  </span>
                )}
              </label>
              <div className="flex gap-1.5">
                <input
                  type="text"
                  value={teacherId}
                  onChange={(e) => handleIdChange(e.target.value)}
                  disabled={isEdit}
                  placeholder="e.g. T_ROHIT_VERMA"
                  className="flex-1 min-w-0 bg-slate-50 disabled:bg-slate-100/70 border border-slate-300 rounded-xl px-3 py-2 text-xs font-mono font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500"
                />
                {!isEdit && !idAutoGenerated && (
                  <button
                    type="button"
                    onClick={resetAutoId}
                    title="Re-generate ID from name"
                    className="px-2 py-1.5 rounded-lg border border-emerald-200 bg-emerald-50 text-emerald-700 hover:bg-emerald-100 transition-colors cursor-pointer shrink-0"
                  >
                    <Wand2 className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
              {isEdit && (
                <span className="text-[10px] text-slate-400 mt-0.5 block">
                  ID cannot be changed once created.
                </span>
              )}
            </div>

            {/* Department */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Department
              </label>
              <select
                value={department}
                onChange={(e) => setDepartment(e.target.value)}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500"
              >
                {DEPARTMENTS.map((d) => (
                  <option key={d} value={d}>{d}</option>
                ))}
              </select>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
            {/* Max Hours Per Day */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Max Daily Workload <span className="text-rose-500">*</span>
              </label>
              <input
                type="number"
                min={1}
                max={8}
                value={maxHoursPerDay}
                onChange={(e) => setMaxHoursPerDay(Number(e.target.value))}
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs font-bold text-slate-900 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500"
                required
              />
              <span className="text-[10px] text-slate-500 mt-0.5 block">
                Max periods taught per day (1–8)
              </span>
            </div>

            {/* Homeroom */}
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">
                Homeroom Class <span className="text-slate-400 font-normal">(optional)</span>
              </label>
              <input
                type="text"
                value={homeroomClass}
                onChange={(e) => setHomeroomClass(e.target.value)}
                placeholder="e.g. Grade 9-A"
                className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500"
              />
            </div>
          </div>

          {/* Email */}
          <div>
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Email <span className="text-slate-400 font-normal">(optional)</span>
            </label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="e.g. rohit.verma@school.edu"
              className="w-full bg-slate-50 border border-slate-300 rounded-xl px-3 py-2 text-xs text-slate-800 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-500"
            />
          </div>

          {/* Unavailable Time Slot Picker */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <label className="text-xs font-semibold text-slate-700">
                Unavailable Time Slots
                <span className="text-slate-400 font-normal ml-1">(click cells to block)</span>
              </label>
              {unavailableSlots.size > 0 && (
                <button
                  type="button"
                  onClick={() => setUnavailableSlots(new Set())}
                  className="text-[10px] text-rose-500 hover:text-rose-700 font-semibold cursor-pointer"
                >
                  Clear all
                </button>
              )}
            </div>

            {/* Grid Picker */}
            <div className="rounded-xl border border-slate-200 overflow-hidden bg-slate-50">
              <table className="w-full text-[10px] border-collapse">
                <thead>
                  <tr className="bg-slate-100">
                    <th className="px-2 py-1.5 text-slate-500 font-semibold text-left border-r border-slate-200 w-12">
                      Period
                    </th>
                    {DAYS.map((day) => (
                      <th key={day} className="px-1 py-1.5 text-slate-700 font-bold text-center border-r border-slate-200 last:border-r-0">
                        {day}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {PERIODS.map((period) => (
                    <tr key={period} className="border-t border-slate-200">
                      <td className="px-2 py-1 text-slate-500 font-semibold border-r border-slate-200 text-center bg-slate-100/60">
                        P{period}
                      </td>
                      {DAYS.map((day) => {
                        const key = `${day}:${period}`;
                        const blocked = unavailableSlots.has(key);
                        return (
                          <td
                            key={day}
                            onClick={() => toggleSlot(day, period)}
                            title={blocked ? `Remove ${day} P${period}` : `Block ${day} P${period}`}
                            className={`text-center cursor-pointer border-r border-slate-200 last:border-r-0 transition-colors select-none ${
                              blocked
                                ? "bg-rose-100 text-rose-700 font-bold"
                                : "hover:bg-slate-200 text-transparent"
                            }`}
                            style={{ height: "22px" }}
                          >
                            {blocked ? "✕" : "·"}
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Summary string */}
            {unavailableSlots.size > 0 ? (
              <p className="text-[10px] text-slate-500 mt-1 font-mono">
                → {unavailableTimesString}
              </p>
            ) : (
              <p className="text-[10px] text-slate-400 mt-1">
                No slots blocked — teacher is available all day every day.
              </p>
            )}
          </div>

          {/* Footer Actions */}
          <div className="pt-3 border-t border-slate-100 flex items-center justify-end gap-2.5 shrink-0">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="px-4 py-2 rounded-xl border border-slate-200 text-xs font-semibold text-slate-700 hover:bg-slate-50 transition-colors cursor-pointer"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="inline-flex items-center gap-2 px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-700 disabled:opacity-60 text-white text-xs font-semibold shadow-xs transition-all cursor-pointer"
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  <span>Saving...</span>
                </>
              ) : (
                <span>{isEdit ? "Update Faculty" : "Create Faculty"}</span>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
